name = "SimpleGraphAlgorithms"
uuid = "41400c72-0c58-5c16-8579-4ecbce768449"
version = "0.5.0"

[deps]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
ChooseOptimizer = "858a232f-1959-5553-8cfc-91e1fd5304e2"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SimpleGraphs = "55797a34-41de-5266-9ec1-32ac4eb504d3"
SimplePartitions = "ec83eff0-a5b5-5643-ae32-5cbf6eedec9d"
SimplePolynomials = "cc47b68c-3164-5771-a705-2bc0097375a0"

[compat]
Cbc = "0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.10, 1"
GLPK = "1"
ChooseOptimizer = "0.1, 0.2"
JuMP = "0.18, 0.19, 0.20, 0.21, 0.22, 1"
SimpleGraphs = "0.8"
SimplePartitions = "0.0.1, 0.1, 0.2, 0.3"
SimplePolynomials = "0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.1, 0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
